name: Launcher Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13.2
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.2

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt -r requirements-dev.txt

      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          include-package-data: |
           minecraft_launcher_lib:version.txt
           flet
           assets
          output-file: cube-launcher
          script-name: main.py
          mode: app

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}_build
          path: |
            build/cube-launcher.exe
            build/cube-launcher
          include-hidden-files: true
