name: Launcher Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
            enable-cache: true
            cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          include-package-data: |
           minecraft_launcher_lib:version.txt
           flet
           assets
          output-file: cube-launcher
          windows-console-mode: disable
          script-name: main.py
          mode: app

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}_build
          path: |
            build/cube-launcher.exe
            build/cube-launcher
          include-hidden-files: true

      - name: Minimize uv cache
        run: uv cache prune --ci