name: Launcher Dev-Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    
    permissions:
      contents: write
      pages: write
      id-token: write
      attestations: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          activate-environment: true

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run script
        run: |
          python update_version.py --dev

      - name: Pack Flet app
        shell: bash
        run: |
          flet pack \
            --name cube-launcher \
            --yes \
            --add-data=assets:assets \
            main.py 
        working-directory: .

      - name: Sign with cosign (keyless)
        if: runner.os == 'Windows'
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign-blob --yes --output-signature "dist/cube-launcher.exe.sig" "dist/cube-launcher.exe"

      - name: Sign Windows Executable
        if: runner.os == 'Windows'
        uses: skymatic/code-sign-action@v3
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          password: '${{ secrets.CERT_PASSWORD }}'
          certificatesha1: '${{ secrets.CERTHASH }}'
          certificatename: '${{ secrets.CERTNAME }}'
          description: 'Cube Launcher'
          timestampUrl: 'http://timestamp.digicert.com'
          folder: 'dist'
          recursive: false

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ./dist/*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}
          path: |
            dist/cube-launcher.exe
            dist/cube-launcher.exe.sig
            dist/cube-launcher
          include-hidden-files: true

      - name: Minimize uv cache
        run: uv cache prune --ci
