name: Launcher Release-Build

on:
  push:
    tags:
      - 'v*.*.*' # Matches version tags like v1.0.0

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
            enable-cache: true
            activate-environment: true

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run script
        run: |
          python update_version.py --release

      - name: Pack Flet app
        shell: bash
        run: |
          flet pack \
            --name cube-launcher \
            --yes \
            --add-data=assets:assets \
            main.py 
        working-directory: .

      - name: Sign with cosign (keyless)
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          for file in dist/*.exe; do
            cosign sign-blob --yes --output-signature "${file}.sig" "$file"
          done
        
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
          make_latest: true
          files: |
            dist/*
            dist/*.sig
        continue-on-error: true

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ./dist/*

      - name: Minimize uv cache
        run: uv cache prune --ci